from __future__ import annotations
import uuid
from pmm.execution.exchange_base import ExchangeBase, PlaceOrderResult

class PaperExchange(ExchangeBase):
    """
    Extremely conservative paper execution:
    - We accept order placement always.
    - We do NOT simulate queue priority; fills are generated by strategy/risk module (or by later extensions).
    This is intentionally minimal: the key deliverable is full journaling + trade tape comparability to live.
    """
    is_paper = True

    def place_limit(self, *, token_id: str, side: str, price: float, size: float, post_only: bool, meta: dict) -> PlaceOrderResult:
        # Paper venue order id is a UUID-like string.
        return PlaceOrderResult(success=True, venue_order_id=f"paper-{uuid.uuid4()}", raw={"mode":"paper"})

    def cancel(self, *, venue_order_id: str) -> bool:
        return True
